# Generated by Django 5.1 on 2024-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('iphone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('year_of_birth', models.CharField(max_length=100, verbose_name='Год рождения')),
                ('job_title', models.CharField(max_length=100, verbose_name='На какую вакаснию вы хотите попасть ?')),
                ('experience', models.TextField(verbose_name='Ваш опыт работы ')),
                ('about_myself', models.TextField(verbose_name='Расскажите о себе')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
            },
        ),
    ]
